

import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jakepalmer
 */
public class MainFrame extends javax.swing.JFrame {

    //Game
    static Gameboard gameBoard = new Gameboard(3);    
    int dimensions;
    
    Opponent compPlayer;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        dimensions = 3;        
        gameBoard = new Gameboard(dimensions);        
        compPlayer = new Opponent();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 600), new java.awt.Dimension(0, 600), new java.awt.Dimension(32767, 600));
        boardPanel = new MyPanel();
        hexaPawnBtn = new javax.swing.JButton();
        pentaPawnBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        consoleTextArea = new javax.swing.JTextArea();
        consoleBoardBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boardPanel.setBackground(new java.awt.Color(255, 255, 255));
        boardPanel.setMaximumSize(new java.awt.Dimension(600, 600));
        boardPanel.setMinimumSize(new java.awt.Dimension(600, 600));
        boardPanel.setPreferredSize(new java.awt.Dimension(600, 600));
        boardPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                boardPanelMouseDragged(evt);
            }
        });
        boardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boardPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boardPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        hexaPawnBtn.setText("Hexa-Pawn");
        hexaPawnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexaPawnBtnActionPerformed(evt);
            }
        });

        pentaPawnBtn.setText("Penta-Pawn");
        pentaPawnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pentaPawnBtnActionPerformed(evt);
            }
        });

        consoleTextArea.setColumns(20);
        consoleTextArea.setRows(5);
        jScrollPane2.setViewportView(consoleTextArea);

        consoleBoardBtn.setText("Show Board");
        consoleBoardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleBoardBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Show bool");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pentaPawnBtn)
                            .addComponent(hexaPawnBtn)
                            .addComponent(consoleBoardBtn)
                            .addComponent(jButton1))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(hexaPawnBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pentaPawnBtn)
                            .addGap(54, 54, 54)
                            .addComponent(consoleBoardBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1)
                            .addGap(99, 99, 99)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hexaPawnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexaPawnBtnActionPerformed
        // TODO add your handling code here:
        dimensions = 3;        
        gameBoard = new Gameboard(dimensions);        

        repaint();
    }//GEN-LAST:event_hexaPawnBtnActionPerformed

    private void pentaPawnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pentaPawnBtnActionPerformed
        // TODO add your handling code here:        
        dimensions = 4;
        System.out.println("dimensions = " + dimensions);
        gameBoard = new Gameboard(dimensions);
          
        repaint();
    }//GEN-LAST:event_pentaPawnBtnActionPerformed

    private void consoleBoardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleBoardBtnActionPerformed
        // TODO add your handling code here:       
        if (gameBoard != null) {
            consoleTextArea.append("------\n" + gameBoard.toString() + "------\n");
        } else {
            System.out.println("Not Yet!...");
        }
    }//GEN-LAST:event_consoleBoardBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        consoleTextArea.append(gameBoard.toBoolString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boardPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardPanelMousePressed
        // TODO add your handling code here:
        if (!gameBoard.isGameOver()) {
            gameBoard.setMouse(evt.getX(), evt.getY());
            gameBoard.handlePressed(evt.getX(), evt.getY());
            repaint();
        }
    }//GEN-LAST:event_boardPanelMousePressed

    private void boardPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardPanelMouseReleased
        // TODO add your handling code here:
        gameBoard.setMouse(evt.getX(), evt.getY());

        if (gameBoard.handleRealesed(evt.getX(), evt.getY())) {
            if ((gameBoard.getCurrentTurn() == -1) && (!gameBoard.isGameOver())) {
                repaint();
                try {
                    gameBoard.makeMove(compPlayer.selectRandomMoveAndLearn(gameBoard));
                } catch (CloneNotSupportedException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                repaint();
            } else {
                if (gameBoard.isGameOver()) {     
                    
                    if (gameBoard.getCurrentTurn() == -1) {
                        consoleTextArea.append("GameOver! You won! \n" );
                        compPlayer.recordLoss();
                    } 
                }
            }

        }

        repaint();

    }//GEN-LAST:event_boardPanelMouseReleased

    private void boardPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardPanelMouseDragged
        // TODO add your handling code here:
        gameBoard.setMouse(evt.getX(), evt.getY());
        repaint();
        
    }//GEN-LAST:event_boardPanelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }


    
    
    
    
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardPanel;
    private javax.swing.JButton consoleBoardBtn;
    private javax.swing.JTextArea consoleTextArea;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton hexaPawnBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton pentaPawnBtn;
    // End of variables declaration//GEN-END:variables

}
